import type { RecommendationResponse, RecommendationRequest } from "@/lib/types/wish";

export function getMockRecommendation(req: RecommendationRequest): RecommendationResponse {
  const mbti = req.profile.mbti ?? "INTJ";
  const income = req.profile.annualIncome ?? 200000;
  const isAnalytical = ["INTJ", "INTP", "ENTJ", "ENTP"].includes(mbti);
  const isDiplomatic = ["INFJ", "INFP", "ENFJ", "ENFP"].includes(mbti);

  const wishes: RecommendationResponse = {
    summary: `基于你的 ${mbti} 性格与 ¥${income.toLocaleString("en-US")} 年收入约束，老赫为你设计了 10 个能在 ${req.life.remainingYears.toFixed(0)} 年内实现的人生体验。`,
    generatedAt: new Date().toISOString(),
    source: "mock",
    wishes: [
      {
        id: "wish-1",
        title: "在冰岛黑沙滩等一场天幕极光",
        description: "零下二十度的 Vík 黑沙滩，玄武岩柱沉默如远古祭坛，等绿色极光覆盖整个天幕。",
        category: "旅行",
        reason: `${mbti} 的内倾直觉让你能独自消化漫长等待后的震撼，这是水象星座 ${isDiplomatic ? "尤其契合" : "可以挑战"}的体验。`,
        personalityFitScore: 92,
        estimatedCost: { min: 18000, max: 28000, currency: "CNY" },
        estimatedDuration: "8-10 天",
        timeWindow: "11 月 - 3 月（极夜季节）",
        location: { name: "冰岛 · 维克黑沙滩", country: "Iceland", countryCode: "IS", lat: 63.4185, lng: -19.0064 },
        prerequisites: ["申根签证", "冰岛克朗兑换", "防风羽绒服"],
      },
      {
        id: "wish-2",
        title: "在京都哲学之道走完一整个樱花季",
        description: "从若王子神社到银阁寺，2 公里的樱隧道，每天去走一遍，看花瓣飘落琵琶湖水。",
        category: "体验",
        reason: `${isAnalytical ? mbti + " 的深思倾向与哲学之道的名字共鸣" : mbti + " 的内省能量需要这种慢节奏的审美沉浸"}。`,
        personalityFitScore: 89,
        estimatedCost: { min: 8000, max: 15000, currency: "CNY" },
        estimatedDuration: "5-7 天",
        timeWindow: "3 月底 - 4 月初",
        location: { name: "京都 · 哲学之道", country: "Japan", countryCode: "JP", lat: 35.0279, lng: 135.7944 },
        prerequisites: ["日本签证", "樱花前线 App"],
      },
      {
        id: "wish-3",
        title: "在喜马拉雅 EBC 大本营重新校准人生尺度",
        description: "12 天徒步到 5364 米的珠峰南坡大本营，在世界之巅脚下重新理解「大」和「小」。",
        category: "冒险",
        reason: `${mbti} 的判断功能（J）会享受训练计划，剩余 ${req.life.remainingYears.toFixed(0)} 年是身体还能承受的窗口期。`,
        personalityFitScore: 87,
        estimatedCost: { min: 30000, max: 45000, currency: "CNY" },
        estimatedDuration: "14-16 天",
        timeWindow: "3-5 月 / 10-11 月",
        location: { name: "尼泊尔 · EBC 大本营", country: "Nepal", countryCode: "NP", lat: 28.0025, lng: 86.8528 },
        prerequisites: ["半年体能训练", "高海拔药物", "夏尔巴向导"],
      },
      {
        id: "wish-4",
        title: "在巴黎奥赛看完所有印象派原作",
        description: "莫奈、雷诺阿、德加、梵高——把课本上见过的画，一张张站在原作前重新看一遍。",
        category: "学习",
        reason: `${mbti} 的直觉（N）功能对印象派对光影的捕捉会有深度共鸣。`,
        personalityFitScore: 85,
        estimatedCost: { min: 12000, max: 20000, currency: "CNY" },
        estimatedDuration: "5-7 天",
        timeWindow: "全年，避开 7-8 月旺季",
        location: { name: "巴黎 · 奥赛博物馆", country: "France", countryCode: "FR", lat: 48.86, lng: 2.3266 },
        prerequisites: ["申根签证", "Paris Museum Pass"],
      },
      {
        id: "wish-5",
        title: "在沙漠腹地看一整夜银河升起",
        description: "撒哈拉或腾格里的沙丘上，等银河中心从地平线升起，沙子像凝固的海。",
        category: "灵性",
        reason: `${mbti} 对「渺小感」的处理方式独特，星空会让你重新理解存在。`,
        personalityFitScore: 84,
        estimatedCost: { min: 6000, max: 12000, currency: "CNY" },
        estimatedDuration: "3-5 天",
        timeWindow: "4-5 月 / 9-10 月（避开极端高温）",
        location: { name: "摩洛哥 · 梅尔祖卡沙漠", country: "Morocco", countryCode: "MA", lat: 31.098, lng: -4.0128 },
        prerequisites: ["防沙眼镜", "保暖睡袋"],
      },
      {
        id: "wish-6",
        title: "学一门乐器到能完整演奏一首曲子",
        description: "钢琴、小提琴、二胡、卡林巴——选一个，从零开始，6 个月内上台演奏一首完整的曲子。",
        category: "创造",
        reason: `${mbti} 的 ${isAnalytical ? "思维-判断组合适合系统性练习" : "情感功能需要艺术表达出口"}。`,
        personalityFitScore: 82,
        estimatedCost: { min: 3000, max: 10000, currency: "CNY" },
        estimatedDuration: "持续 6 个月",
        timeWindow: "随时开始",
        prerequisites: ["选好老师", "每周固定练习时间"],
      },
      {
        id: "wish-7",
        title: "去非洲看一次完整的大迁徙",
        description: "肯尼亚马赛马拉，百万角马渡马拉河，鳄鱼伏击，尘土遮天。",
        category: "冒险",
        reason: `${mbti} 的直觉能从这种原始生命力中汲取长期能量。`,
        personalityFitScore: 80,
        estimatedCost: { min: 35000, max: 60000, currency: "CNY" },
        estimatedDuration: "10-12 天",
        timeWindow: "7-10 月（迁徙季）",
        location: { name: "肯尼亚 · 马赛马拉", country: "Kenya", countryCode: "KE", lat: -1.4061, lng: 35.0083 },
        prerequisites: ["黄热病疫苗", "高端旅行保险"],
      },
      {
        id: "wish-8",
        title: "和五年后的自己写一封信",
        description: "用三天时间独处，写一封 5000 字的信给五年后的自己，封存，五年后拆开。",
        category: "灵性",
        reason: `${mbti} 的内倾判断需要这种结构化的自我对话。`,
        personalityFitScore: 78,
        estimatedCost: { min: 200, max: 2000, currency: "CNY" },
        estimatedDuration: "一个周末",
        timeWindow: "生日前后",
        prerequisites: ["安静的住所", "纸质信纸"],
      },
      {
        id: "wish-9",
        title: "在新西兰跳一次高空跳伞",
        description: "皇后镇 15000 英尺，60 秒自由落体，200 公里时速俯瞰南阿尔卑斯。",
        category: "冒险",
        reason: `${mbti} 的感觉（S/N）功能会在失重瞬间得到独特体验。`,
        personalityFitScore: 76,
        estimatedCost: { min: 3000, max: 5000, currency: "CNY" },
        estimatedDuration: "1 天",
        timeWindow: "全年天气允许时",
        location: { name: "新西兰 · 皇后镇", country: "New Zealand", countryCode: "NZ", lat: -45.0312, lng: 168.6626 },
        prerequisites: ["无心脏病", "体重 100kg 以下"],
      },
      {
        id: "wish-10",
        title: "和父母做一次深度的口述史访谈",
        description: "录制 3-5 小时视频，问他们童年、爱情、遗憾、对死亡的看法。剪辑成纪录片。",
        category: "关系",
        reason: `${mbti} 剩余 ${req.life.remainingYears.toFixed(0)} 年里，父母可陪伴的窗口更短，这件事不可推迟。`,
        personalityFitScore: 95,
        estimatedCost: { min: 500, max: 3000, currency: "CNY" },
        estimatedDuration: "持续 1 个月",
        timeWindow: "春节 / 国庆（家族聚会时）",
        prerequisites: ["录音录像设备", "访谈大纲"],
      },
    ].sort((a, b) => b.personalityFitScore - a.personalityFitScore),
  };

  return wishes;
}
